server:
  port: 8080

spring:
  application:
    name: library-monolith

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
